name: CI

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.19.5'
    - name: Build
      run: |
        go version
        make build-all
        ls -lh _releases/
